// src/app/components/projectsData.js
const projectsData = [
    {
      id: 3,
      title: "Varausjärjestelmä",
      description: "Ajanvarausjärjestelmä yrityksille ja asiakkaille.",
      image: "/images/projects/3.png",
      technologies: ["React", "Next.js", "TailwindCSS"],
      challenges: ["Ajanvarauksen hallinta", "Sujuva käyttäjäkokemus"],
      gitUrl: "https://github.com/Tamamkarim/SAS-2.0-N",
      previewUrl: "/",
      video: "",
    },
    {
      id: 1,
      title: "React Portfolio-sivusto",
      description: "Henkilökohtainen portfolio-sivusto rakennettu Reactilla ja Next.js:llä.",
      image: "/images/projects/1.png",
      technologies: ["React", "Next.js", "TailwindCSS"],
      challenges: ["Responsiivinen suunnittelu", "Tumman tilan tuki"],
      gitUrl: "https://github.com/Tamamkarim/porfolio_website-2",
      previewUrl: "/",
      video: "",
    },
    {
      id: 2,
      title: "Apricus - Kahvila & Ravintola",
      description: "Ravintolan ja kahvilan sivusto, jossa on ruokalista ja varausmahdollisuus.",
      image: "/images/projects/Ravintaloa.Kahvila.png",
      technologies: ["React", "Next.js", "CSS"],
      challenges: ["Houkutteleva käyttöliittymä", "Varausten hallinta"],
      gitUrl: "https://github.com/Tamamkarim/projakti-web-Ravintolakonsepti#",
      previewUrl: "/",
      video: "",
    },
    {
      id: 4,
      title: "Sääsovellus",
      description: "Sovellus, joka näyttää reaaliaikaiset säätiedot eri kaupungeista.",
      image: "/images/projects/weather-app.png",
      technologies: ["React", "OpenWeatherMap API", "CSS"],
      challenges: ["API-integraatio", "Dynaaminen käyttöliittymä"],
      gitUrl: "https://github.com/Tamamkarim/weather-app",
      previewUrl: "/",
      video: "",
    },
    {
      id: 5,
      title: "Tehtävienhallinta",
      description: "Tehtävienhallintasovellus, jossa on mahdollisuus lisätä, muokata ja poistaa tehtäviä.",
      image: "/images/projects/todo-app.png",
      technologies: ["React", "Redux", "CSS"],
      challenges: ["Tilanhallinta", "Käyttäjäystävällinen suunnittelu"],
      gitUrl: "https://github.com/Tamamkarim/todo-app",
      previewUrl: "/",
      video: "",
    },
        {
      id: 6,
      title: "Lokkit_web",
      description: "Project ",
      image: "/images/projects/7.png",
      technologies: ["React", "Next.js", "TailwindCSS"],
      challenges: ["Ajanvarauksen hallinta", "Sujuva käyttäjäkokemus"],
      gitUrl: "https://github.com/Tamamkarim/Dockre",
      previewUrl: "/",
      video: "",
    }, 
    {
      id: 7,
      title: " Ravintola",
      description: "",
      image: "/images/projects/Raventaloa2.png",
      technologies: ["React", "Next.js", "TailwindCSS"],
      challenges: ["Ajanvarauksen hallinta", "Sujuva käyttäjäkokemus"],
      gitUrl: "https://github.com/Tamamkarim/Food-TK",
      previewUrl: "/",
      video: "",
    },
    {
      id: 8,
      title: " Game",
      description: "",
      image: "/images/projects/99.png",
      technologies: ["React", "Next.js", "TailwindCSS"],
      challenges: ["Ajanvarauksen hallinta", "Sujuva käyttäjäkokemus"],
      gitUrl: "https://github.com/Tamamkarim/proikti_game",
      previewUrl: "/",
      video: "",
    },
    


];

export default projectsData;
